name: Node.js Package
on:
  release:
    types: [created]
jobs:
  build:
    name: Github Packages Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # GitHub Packagesへの公開のために.npmrcファイルをセットアップ
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@hisasann' # Defaults to the user or organization that owns the workflow file
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
